### ISSUE TITLE
Support request

### ISSUE THREAD

**Issue by lukwil** [openfaas-incubator/nats-connector#16]
Hi, first of all: Thank you for building this great product and especially the NATS connector!

I hooked up multiple topics to the NATS connector, but it keeps restarting every once in a while. My messages are getting through thus there should be no problem, but I consider a failing container not a periodically failing container unfavorable for the stability of my product development. 

I also checked the logs and the last log line before it backs off and restarts is always something like 

`2020/09/01 20:21:38 invalid character 'u' looking for beginning of value`

I tried everything I could possibly think of, but could not find a solution. It might have something to do with (JSON) deserialization, but that should not be a problem concerning the connector.

**Comment by alexellis** [comment]
We'll need full instructions and logs to help you. Can you do that and get back to us? Maybe a sample Function would help too. 

Btw OpenFaaS isnt a product, it's a free and open source project made available by volunteers.

**Comment by n8britton** [comment]
Hello, this is happening for me as well and I have not been able to find a fix.

THis is the full dump of the logs:

```
==============================================================================
NATS Connector for OpenFaaS

Gateway URL: http://gateway.default.svc.cluster.local:8080
NATS URL: nats://nats-cluster.default.svc.cluster.local:4222
Topics: 1m1s
Upstream timeout: [natstest]
Topic-map rebuild interval: 5s
Async invocation: "false"
==============================================================================

2021/01/20 19:54:31 invalid character 'i' looking for beginning of value
```


It is interesting to note that the variables print out of order in this log entry.  Is there a debug mode that can be enabled?

Here is the config.yaml
```
15:37 $ cat connector-dep.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nats-connector
    component: nats-connector
  name: nats-connector
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-connector
      component: nats-connector
  template:
    metadata:
      labels:
        app: nats-connector
        component: nats-connector
    spec:
      containers:
      - name: nats-connector
        image: openfaas/nats-connector:0.2.1
        env:
          - name: upstream_timeout
            value: "1m1s"
          - name: broker_host
            value: "nats-cluster.default.svc.cluster.local"
          - name: gateway_url
            value: "http://gateway.default.svc.cluster.local:8080"
          - name: topics
            value: "natstest,"
          - name: print_response
            value: "true"
          - name: print_response_body
            value: "true"
          - name: basic_auth
            value: "true"
          - name: secret_mount_path
            value: "/var/secrets/"
          - name: topic_delimiter
            value: ","
          - name: asynchronous_invocation
            value: "false"
        volumeMounts:
            - name: auth
              readOnly: true
              mountPath: "/var/secrets/"
      volumes:
      - name: auth
        secret:
          secretName: basic-auth
```
